/*
 * EXTINT0_Config.h
 *
 *  Created on: Apr 4, 2023
 *      Author: Ayman ahmed
 */

#ifndef MCAL_EXTINT0_CONFIG_H_
#define MCAL_EXTINT0_CONFIG_H_
#include "EXTINT0_Private.h"
#define CaseINT0 INT0_FallingEdge

#define ENABLEINT0_LOW_LEVEL \
CLEAR_BIT(MCUCR_Reg,ISC00);\
CLEAR_BIT(MCUCR_Reg,ISC01)

#define ENABLEINT0_ANY_LOGIC \
SET_BIT(MCUCR_Reg,ISC00);\
CLEAR_BIT(MCUCR_Reg,ISC01)

#define ENABLEINT0_FALLING_EDGE \
CLEAR_BIT(MCUCR_Reg,ISC00);\
SET_BIT(MCUCR_Reg,ISC01)

#define ENABLEINT0_RISING_EDGE \
SET_BIT(MCUCR_Reg,ISC00);\
SET_BIT(MCUCR_Reg,ISC01)

#define ENABLEINT0_GICR_Reg SET_BIT(GICR_Reg,GICR_INT0_BIT)
#endif /* MCAL_EXT_INT_EXTINT0_CONFIG_H_ */
